export interface StudioInfo {
  /** Unique GUID generated by the Studio plugin */
  studioId: string;
  /** Name of the place open in this Studio */
  placeName: string;
  /** Roblox Place ID (if published) */
  placeId?: number;
  /** Roblox Game/Universe ID (if published) */
  gameId?: number;
  /** When this studio first registered */
  registeredAt: number;
  /** Last time this studio polled for commands */
  lastPoll: number;
}

export interface PluginResponse {
  success: boolean;
  data?: unknown;
  error?: string;
}

/** Port range the HTTP server tries to bind to */
export const HTTP_PORT_START = 3002;
export const HTTP_PORT_END = 3020;

/** How long before a non-polling studio is considered dead (ms) */
export const STUDIO_TIMEOUT = 15000;

/** How long to wait for a plugin to respond to a queued command (ms) */
export const REQUEST_TIMEOUT = 30000;
